//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompassionFinal
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class DETALLE_LESION
    {
        public int IDdetalleLes { get; set; }
        
        public int IDincidente { get; set; }
        public int tipo_lesion { get; set; }
        public string cometario { get; set; }
    
        public virtual INCIDENTE_MEDICO INCIDENTE_MEDICO { get; set; }
        public virtual LESION LESION { get; set; }
    }
}
