//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompassionFinal
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class DETALLE_ENFERMEDAD
    {
        public int IDdetalleEnf { get; set; }
        public int idincidente { get; set; }
        public int categoria { get; set; }
        public int subcategoria { get; set; }
        public string descripcion { get; set; }
    
        public virtual CATEGORIA_ENFERMEDAD CATEGORIA_ENFERMEDAD { get; set; }
        public virtual INCIDENTE_MEDICO INCIDENTE_MEDICO { get; set; }
        public virtual SUBCATEGORIA_ENFERMEDAD SUBCATEGORIA_ENFERMEDAD { get; set; }
    }
}
