//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompassionFinal
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Linq;
    public partial class Hogar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Hogar()
        {
            this.miembros_hogar = new HashSet<miembros_hogar>();
            this.Niño = new HashSet<Niño>();
        }
    
        public int Idhogar { get; set; }
       [Required] public string nombre { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<miembros_hogar> miembros_hogar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Niño> Niño { get; set; }
        public List<Hogar> Todo()
        {
            var hogares = new List<Hogar>();
            try
            {
                using (var db = new Entities1())
                {
                    hogares = db.Hogar.ToList();
                }
            }
            catch (Exception)
            {

                throw;
            }
            return hogares;
        }
    }
}
