//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompassionFinal
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class miembros_hogar
    {
        public int Idmiembro { get; set; }
        [Required]
        [Display(Name = "Hogar")]
        public int idhogar { get; set; }
        [Required]
        [Display(Name = "Nombre")]
        public string nombres { get; set; }
        [Required]
        [Display(Name = "Rol")]
        public int idrol { get; set; }
        public Nullable<bool> cuidador { get; set; }
    
        public virtual Hogar Hogar { get; set; }
        public virtual Rol Rol { get; set; }
    }
}
