//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompassionFinal
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities1 : DbContext
    {
        public Entities1()
            : base("name=Entities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<ASISTENCIA> ASISTENCIA { get; set; }
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaims> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogins> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<CATEGORIA_ENFERMEDAD> CATEGORIA_ENFERMEDAD { get; set; }
        public virtual DbSet<DETALLE_ENFERMEDAD> DETALLE_ENFERMEDAD { get; set; }
        public virtual DbSet<DETALLE_HORARIO> DETALLE_HORARIO { get; set; }
        public virtual DbSet<DETALLE_INMUNIZACIONES> DETALLE_INMUNIZACIONES { get; set; }
        public virtual DbSet<DETALLE_LESION> DETALLE_LESION { get; set; }
        public virtual DbSet<DIAS> DIAS { get; set; }
        public virtual DbSet<DOSIS> DOSIS { get; set; }
        public virtual DbSet<ESTADO> ESTADO { get; set; }
        public virtual DbSet<genero> genero { get; set; }
        public virtual DbSet<GRADO_INSTRUCCION> GRADO_INSTRUCCION { get; set; }
        public virtual DbSet<GRUPO_CLASE> GRUPO_CLASE { get; set; }
        public virtual DbSet<Hogar> Hogar { get; set; }
        public virtual DbSet<INCIDENTE_MEDICO> INCIDENTE_MEDICO { get; set; }
        public virtual DbSet<LESION> LESION { get; set; }
        public virtual DbSet<miembros_hogar> miembros_hogar { get; set; }
        public virtual DbSet<Niño> Niño { get; set; }
        public virtual DbSet<Nivel> Nivel { get; set; }
        public virtual DbSet<PERIODO> PERIODO { get; set; }
        public virtual DbSet<Rol> Rol { get; set; }
        public virtual DbSet<SUBCATEGORIA_ENFERMEDAD> SUBCATEGORIA_ENFERMEDAD { get; set; }
        public virtual DbSet<Tipo> Tipo { get; set; }
        public virtual DbSet<TIPO_INMUNIZACION> TIPO_INMUNIZACION { get; set; }
        public virtual DbSet<TUTOR> TUTOR { get; set; }
    }
}
