//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompassionFinal
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Linq;
    public partial class Niño
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Niño()
        {
            this.ASISTENCIA = new HashSet<ASISTENCIA>();
            this.DETALLE_INMUNIZACIONES = new HashSet<DETALLE_INMUNIZACIONES>();
            this.INCIDENTE_MEDICO = new HashSet<INCIDENTE_MEDICO>();
        }
        [Required]
        [StringLength(4)]
        [Display(Name = "ID|Código")]
        public string Idniño { get; set; }
        [Required]
        [StringLength(30)]
        public string Nombres { get; set; }
        [Required]
        [Display(Name = "Familia")]
        public int Idhogar { get; set; }
        [Required]
        [Display(Name = "Género")]
        public int Genero { get; set; }
        [Required]
        [StringLength(8)]
        public string DNI { get; set; }
        [Required]
        [DataType(DataType.Date)]
        [Display(Name = "F/Nacimiento")]
        public System.DateTime fechanacimiento { get; set; }
        [Required]
        [Display(Name = "Nivel")]
        public int nivel { get; set; }
        [Required]
        [StringLength(50)]
        [Display(Name = "Dirección")]
        public string direccion { get; set; }
        [Required]
        [Display(Name = "Clase")]
        public int Grupo_clase { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ASISTENCIA> ASISTENCIA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DETALLE_INMUNIZACIONES> DETALLE_INMUNIZACIONES { get; set; }
        public virtual genero genero1 { get; set; }
        public virtual GRUPO_CLASE GRUPO_CLASE1 { get; set; }
        public virtual Hogar Hogar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<INCIDENTE_MEDICO> INCIDENTE_MEDICO { get; set; }
        public virtual Nivel Nivel1 { get; set; }
    }
}
