//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompassionFinal
{
    using System;
    using System.Collections.Generic;
    
    public partial class SUBCATEGORIA_ENFERMEDAD
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SUBCATEGORIA_ENFERMEDAD()
        {
            this.DETALLE_ENFERMEDAD = new HashSet<DETALLE_ENFERMEDAD>();
        }
    
        public int IDSubEnf { get; set; }
        public string nombre { get; set; }
        public Nullable<int> categoria { get; set; }
    
        public virtual CATEGORIA_ENFERMEDAD CATEGORIA_ENFERMEDAD { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DETALLE_ENFERMEDAD> DETALLE_ENFERMEDAD { get; set; }
    }
}
