//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CompassionFinal
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TIPO_INMUNIZACION
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TIPO_INMUNIZACION()
        {
            this.DETALLE_INMUNIZACIONES = new HashSet<DETALLE_INMUNIZACIONES>();
        }
    
        public int IDT_Inmunizacion { get; set; }
        public string nombre { get; set; }
        public int nro_dosis { get; set; }
        public int periodo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DETALLE_INMUNIZACIONES> DETALLE_INMUNIZACIONES { get; set; }
    }
}
